IVYPORTAL-10766 Improve GUI test - Tried to stabilized and added code to analyzed ChatTest at vn.wawa.guitest.base.client.Browser.shutdown(Browser.java:67)  at portal.guitest.common.ScreenshotFailedTestRule$1.evaluate(ScreenshotFailedTestRule.java:34) Session ID is null. Using WebDriver after calling quit()? - Tried to stabilized ProcessWidgetTest.testReorderFavoriteProcess at portal.guitest.test.ProcessWidgetTest.testReorderFavoriteProcess(ProcessWidgetTest.java:177) expected:<[Case Map: Leave Request]> but was:<[AGoogle]> - Stabilized taking screenshot StatisticScreenshotTest.screenshotForStatistic  at portal.guitest.page.TemplatePage.waitForElementDisplayed(TemplatePage.java:51) at portal.guitest.page.TemplatePage.waitForElementDisplayed(TemplatePage.java:130) at portal.guitest.page.HomePage.waitForStatisticRendered(HomePage.java:43) - Archived engine log to analyze more